# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_basis_sp <- function(X, cc, w) {
    .Call(`_stcos_compute_basis_sp`, X, cc, w)
}

compute_basis_spt <- function(X, cc, w_s, w_t) {
    .Call(`_stcos_compute_basis_spt`, X, cc, w_s, w_t)
}

eigs_sym <- function(X, k) {
    .Call(`_stcos_eigs_sym`, X, k)
}

pinv <- function(X) {
    .Call(`_stcos_pinv`, X)
}

sample_Gamma0_VAR1 <- function(A, Sigma, R, burn = 10000L) {
    .Call(`_stcos_sample_Gamma0_VAR1`, A, Sigma, R, burn)
}

seq_int_ordered <- function(from, to) {
    .Call(`_stcos_seq_int_ordered`, from, to)
}

